### ISSUE TITLE
README.md missing `+esp` toolchain argument

### ISSUE THREAD

**Issue by cgranade** [verylowfreq/rust_on_m5stack_example#1]
When running `cargo build` inside the devcontainer for this example, `stable` is the default toolchain such that an error results when building the crate:

```
root@e2f1491b808e:/workspaces/rust_on_m5stack_example# cargo build
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target xtensa-esp32-espidf --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "xtensa-esp32-espidf". Run `rustc --print target-list` for a list of built-in targets
```

The error is resolved by running `cargo +esp build` instead to use the toolchain provided by the espressif/idf-rust-examples Docker image listed in the `FROM` line of this repo's Dockerfile.

Thanks for making this awesome example! 💕

**Comment by verylowfreq** [comment]
Thank you very much!

I've committed changes including the update of README.
